# Generated by Django 5.2 on 2025-04-21 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_payment_payment_provider'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WayForPayPayment',
        ),
    ]
