# Generated by Django 5.2 on 2025-04-24 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_delete_wayforpaypayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_provider',
            field=models.CharField(choices=[('liqpay', 'LiqPay')], max_length=20),
        ),
    ]
