# Generated by Django 5.2 on 2025-04-26 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_alter_payment_payment_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='provider_payment_id',
        ),
    ]
