# Generated by Django 5.2 on 2025-04-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_alter_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Очікується'), ('completed', 'Завершено'), ('failed', 'Помилка'), ('cancelled', 'Скасовано')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Поповнення'), ('withdrawal', 'Виведення'), ('booking', 'Плата за бронювання')], max_length=20),
        ),
    ]
