# Generated by Django 5.2 on 2025-04-28 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_alter_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Поповнення'), ('withdrawal', 'Виведення')], max_length=20),
        ),
    ]
