# Generated by Django 5.2 on 2025-04-26 20:51

import utils.data_validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userbalance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[utils.data_validation.validate_phone_number]),
        ),
    ]
