# Generated by Django 5.2 on 2025-04-27 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_car_current_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='price_per_day',
        ),
        migrations.RemoveField(
            model_name='car',
            name='price_per_hour',
        ),
    ]
