# Generated by Django 5.2 on 2025-04-27 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_remove_car_deposit_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('petrol', 'Бензин'), ('diesel', 'Дизель'), ('electric', 'Електричний'), ('hybrid', 'Гібрид')], max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('available', 'Доступний'), ('busy', 'Зайнятий'), ('maintenance', 'На обслуговуванні'), ('inactive', 'Неактивний')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('manual', 'Механічна'), ('automatic', 'Автоматична')], max_length=20),
        ),
    ]
