# Generated by Django 5.2 on 2025-04-17 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_booking_status_alter_bookinghistory_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='last_billing_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='minutes_billed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
