# Generated by Django 5.2 on 2025-04-27 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_alter_booking_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='additional_driver',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='baby_seat',
        ),
    ]
