# Generated by Django 5.2 on 2025-04-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_remove_booking_additional_driver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Очікує підтвердження'), ('confirmed', 'Підтверджено'), ('active', 'Активний'), ('completed', 'Завершено'), ('cancelled', 'Скасовано')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='bookinghistory',
            name='status',
            field=models.CharField(choices=[('pending', 'Очікує підтвердження'), ('confirmed', 'Підтверджено'), ('active', 'Активний'), ('completed', 'Завершено'), ('cancelled', 'Скасовано')], max_length=20),
        ),
    ]
